# Generated by Django 3.2.13 on 2023-12-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIFAGen', '0003_alter_profile_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='players',
            new_name='player',
        ),
    ]
