# Generated by Django 3.2.13 on 2023-12-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIFAGen', '0004_rename_players_profile_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='player',
            new_name='players',
        ),
    ]
